name: C++ CI with Google Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Setup GoogleTest
      uses: Bacondish2023/setup-googletest@v1.0.1

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure
